<a href=https://coding.net/event/lottery rel=nofollow>Coding 萌猴抓周抽奖活动正在进行中！快来看看！</a>
<a href=https://coding.net/u/ease>王哼哼</a>合并了项目<a href='https://coding.net/u/coding/p/Coding-iPad'>Coding-iPad</a>的 Pull Request : <a href='https://coding.net/u/coding/p/Coding-iPad/git/pull/56'>#56 修复“ ‘冒泡’ ‘冒泡广场’ 下滑时切换到 ‘好友圈’ 或 ‘热门冒泡’ 时闪退” 的 BUG</a>
<a href=https://coding.net/u/ease>王哼哼</a>合并了项目<a href='https://coding.net/u/coding/p/Coding-iPad'>Coding-iPad</a>的 Pull Request : <a href='https://coding.net/u/coding/p/Coding-iPad/git/pull/56'>#56 修复“ ‘冒泡’ ‘冒泡广场’ 下滑时切换到 ‘好友圈’ 或 ‘热门冒泡’ 时闪退” 的 BUG</a>
<a href=https://coding.net/u/eyrefree>高质量冒泡</a>创建了项目<a href='https://coding.net/u/coding/p/Coding-iPad'>Coding-iPad</a>的 Pull Request : <a href='https://coding.net/u/coding/p/Coding-iPad/git/pull/56'>#56 修复“ ‘冒泡’ ‘冒泡广场’ 下滑时切换到 ‘好友圈’ 或 ‘热门冒泡’ 时闪退” 的 BUG</a>
<a href=https://coding.net/u/ease>王哼哼</a>拒绝了项目<a href='https://coding.net/u/coding/p/Coding-iPad'>Coding-iPad</a>的 Pull Request : <a href='https://coding.net/u/coding/p/Coding-iPad/git/pull/51'>#51 登录页面UI调整</a>
<a href=https://coding.net/u/hbzs>黑白之上</a>创建了项目<a href='https://coding.net/u/coding/p/Coding-iPad'>Coding-iPad</a>的 Pull Request : <a href='https://coding.net/u/coding/p/Coding-iPad/git/pull/51'>#51 登录页面UI调整</a>
<a href=https://coding.net/u/ease>王哼哼</a>合并了项目<a href='https://coding.net/u/coding/p/Coding-iPad'>Coding-iPad</a>的 Pull Request : <a href='https://coding.net/u/coding/p/Coding-iPad/git/pull/49'>#49 2015-12-8 no366</a>
<a href=https://coding.net/u/ease>王哼哼</a>拒绝了项目<a href='https://coding.net/u/coding/p/Coding-iPad'>Coding-iPad</a>的 Pull Request : <a href='https://coding.net/u/coding/p/Coding-iPad/git/pull/46'>#46 No366_Coding-iPad-Debug</a>
<a href=https://coding.net/u/hbzs>黑白之上</a>创建了项目<a href='https://coding.net/u/coding/p/Coding-iPad'>Coding-iPad</a>的 Pull Request : <a href='https://coding.net/u/coding/p/Coding-iPad/git/pull/49'>#49 2015-12-8 no366</a>
<a href=https://coding.net/u/hbzs>黑白之上</a>创建了项目<a href='https://coding.net/u/coding/p/Coding-iPad'>Coding-iPad</a>的 Pull Request : <a href='https://coding.net/u/coding/p/Coding-iPad/git/pull/46'>#46 No366_Coding-iPad-Debug</a>
