<a href=https://coding.net/u/link_biao>link_biao</a>创建了项目<a href='https://coding.net/u/coding/p/Coding-Android'>Coding-Android</a>的 Pull Request : <a href='https://coding.net/u/coding/p/Coding-Android/git/pull/626'>#626 fix 两个评审人相关的 bug</a>
<a href=https://coding.net/u/8206503>陈超</a>合并了项目<a href='https://coding.net/u/coding/p/Coding-Android'>Coding-Android</a>的 Pull Request : <a href='https://coding.net/u/coding/p/Coding-Android/git/pull/613'>#613 对于已经处理的 MR 不能再进入+1 操作，也不能添加移除评审者</a>
<a href=https://coding.net/u/link_biao>link_biao</a>创建了项目<a href='https://coding.net/u/coding/p/Coding-Android'>Coding-Android</a>的 Pull Request : <a href='https://coding.net/u/coding/p/Coding-Android/git/pull/613'>#613 对于已经处理的 MR 不能再进入+1 操作，也不能添加移除评审者</a>
<a href=https://coding.net/u/8206503>陈超</a>合并了项目<a href='https://coding.net/u/coding/p/Coding-Android'>Coding-Android</a>的 Pull Request : <a href='https://coding.net/u/coding/p/Coding-Android/git/pull/609'>#609 MR 相关一系列改动</a>
<a href=https://coding.net/u/link_biao>link_biao</a>创建了项目<a href='https://coding.net/u/coding/p/Coding-Android'>Coding-Android</a>的 Pull Request : <a href='https://coding.net/u/coding/p/Coding-Android/git/pull/609'>#609 MR 相关一系列改动</a>
<a href=https://coding.net/u/8206503>陈超</a>合并了项目<a href='https://coding.net/u/coding/p/Coding-Android'>Coding-Android</a>的 Pull Request : <a href='https://coding.net/u/coding/p/Coding-Android/git/pull/593'>#593 fix MergeRequest 列表页已处理显示的是未处理请求的问题</a>
<a href=https://coding.net/u/link_biao>link_biao</a>创建了项目<a href='https://coding.net/u/coding/p/Coding-Android'>Coding-Android</a>的 Pull Request : <a href='https://coding.net/u/coding/p/Coding-Android/git/pull/593'>#593 fix MergeRequest 列表页已处理显示的是未处理请求的问题</a>
<a href=https://coding.net/event/lottery rel=nofollow>Coding 萌猴抓周抽奖活动正在进行中！快来看看！</a>
<a href=https://coding.net/u/8206503>陈超</a>拒绝了项目<a href='https://coding.net/u/coding/p/Coding-Android'>Coding-Android</a>的 Pull Request : <a href='https://coding.net/u/coding/p/Coding-Android/git/pull/502'>#502 标题显示行数</a>
<a href=https://coding.net/u/leebo>leebo</a>创建了项目<a href='https://coding.net/u/coding/p/Coding-Android'>Coding-Android</a>的 Pull Request : <a href='https://coding.net/u/coding/p/Coding-Android/git/pull/502'>#502 标题显示行数</a>
