# Netscape HTTP Cookie File
# http://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_.coding.net	TRUE	/	TRUE	0	sid	7e26fe61-3084-4550-bb0a-3c48418de952
