# Netscape HTTP Cookie File
# http://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_.coding.net	TRUE	/	TRUE	0	sid	1840baf3-31fc-4ca4-ac64-f8a745be7596
