# Netscape HTTP Cookie File
# http://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_.coding.net	TRUE	/	TRUE	0	sid	a8ef6294-7959-4ed5-b2cf-d96b1109352b
