# Netscape HTTP Cookie File
# http://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_.coding.net	TRUE	/	TRUE	0	sid	d11b3d69-2670-4f9c-8a71-ca6d7c7a8644
