# Netscape HTTP Cookie File
# http://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_.coding.net	TRUE	/	TRUE	0	sid	07bef231-c7d4-4b10-9be9-0499a55be5b6
